### ISSUE TITLE
Mac builds? 

### ISSUE THREAD

**Issue by lobf** [b-crawl/bcrawl#112]
Terribly sorry if this is the wrong place for this, but if you aren't providing mac builds, are there any instructions for compiling on my own? 

I follow this (now kind of outdated) guide for compiling DCSS, but don't know how to adapt to your version:
https://crawl.develz.org/tavern/viewtopic.php?f=9&t=8462&p=114701#p114701

Any chance of having mac builds released in the future with Windows builds?

**Comment by Dust-Finger** [comment]
Try the compile instructions included with source
https://github.com/b-crawl/bcrawl/blob/master/crawl-ref/INSTALL.md

**Comment by lobf** [comment]
Thank you Dust-Finger, I didn't realize those existed. Sorry to bother you guys!
