### ISSUE TITLE
Game Crashes w/ Shield

### ISSUE THREAD

**Issue by Dylan-Dipasupil** [b-crawl/bcrawl#183]
When reporting a bug, please include the following:

**PLATFORM:**
webtiles

**VERSION:**
bcrawl-1.40

**DESCRIPTION:**
When using a medium shield of protection the game would freeze and then crash after engaging with any creature. Game seemed to work fine using a tower shield but when specifically using the medium shield would crash. Was able to consistently get the game to crash by equipping and fighting w/ medium shield.

Crash Log:
[bcrawl-1.40](https://crawl.kelbi.org/crawl/morgue/DylanDipz/crash-DylanDipz-20231023-074420.txt)

**Comment by bhauth** [comment]
Did this fix itself in a couple days? If so it was a server issue, possibly memory capacity related.

**Comment by Dylan-Dipasupil** [comment]
Yes, it was resolved when I came back. Closing issue now.
